[2022-11-04 06:27:49,264][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-04 06:27:49,273][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-04 06:27:49,274][src.utils.rich_utils][WARNING] - Field 'logger' not found in config. Skipping 'logger' config printing...
[2022-11-04 06:27:49,364][__main__][INFO] - Instantiating datamodule <src.datamodules.mnist_datamodule.MNISTDataModule>
[2022-11-04 06:27:49,372][__main__][INFO] - Instantiating model <src.models.mnist_module.MNISTLitModule>
[2022-11-04 06:27:49,444][__main__][INFO] - Instantiating callbacks...
[2022-11-04 06:27:49,445][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-04 06:27:49,450][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-04 06:27:49,452][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-04 06:27:49,453][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-04 06:27:49,454][__main__][INFO] - Instantiating loggers...
[2022-11-04 06:27:49,454][src.utils.utils][WARNING] - Logger config is empty.
[2022-11-04 06:27:49,454][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-04 06:27:49,600][__main__][INFO] - Starting training!
[2022-11-04 06:30:51,851][__main__][INFO] - Starting testing!
[2022-11-04 06:30:54,539][__main__][INFO] - Best ckpt path: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-04_06-27-49/checkpoints/epoch_006.ckpt
[2022-11-04 06:30:54,541][src.utils.utils][INFO] - Closing loggers...
[2022-11-04 06:30:54,543][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-04_06-27-49
[2022-11-04 06:30:54,543][src.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2022-11-05 07:13:37,385][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-05 07:13:37,397][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-05 07:13:37,485][__main__][INFO] - Instantiating datamodule <src.datamodules.mnist_datamodule.MNISTDataModule>
[2022-11-05 07:13:37,491][__main__][INFO] - Instantiating model <src.models.mnist_module.MNISTLitModule>
[2022-11-05 07:13:37,502][__main__][INFO] - Instantiating callbacks...
[2022-11-05 07:13:37,502][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-05 07:13:37,507][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-05 07:13:37,509][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-05 07:13:37,509][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-05 07:13:37,510][__main__][INFO] - Instantiating loggers...
[2022-11-05 07:13:37,510][src.utils.utils][INFO] - Instantiating logger <pytorch_lightning.loggers.wandb.WandbLogger>
[2022-11-05 07:13:40,212][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-05 07:13:40,369][__main__][INFO] - Logging hyperparameters!
[2022-11-05 07:13:40,383][__main__][INFO] - Starting training!
[2022-11-05 07:17:17,837][__main__][INFO] - Starting testing!
[2022-11-05 07:17:20,609][__main__][INFO] - Best ckpt path: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-05_07-13-37/checkpoints/epoch_006.ckpt
[2022-11-05 07:17:20,611][src.utils.utils][INFO] - Closing loggers...
[2022-11-05 07:17:20,612][src.utils.utils][INFO] - Closing wandb!
[2022-11-05 07:17:28,356][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-05_07-13-37
[2022-11-05 07:17:28,357][src.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2022-11-15 20:53:09,292][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 20:53:09,301][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 20:53:09,390][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 20:53:09,597][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 639, in _locate
    obj = getattr(obj, part)
AttributeError: module 'src.datamodules' has no attribute 'chexpert_datamodule'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 645, in _locate
    obj = import_module(mod)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/datamodules/chexpert_datamodule.py", line 9, in <module>
    import albumentations as albu
ModuleNotFoundError: No module named 'albumentations'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 648, in _locate
    raise ImportError(
ImportError: Error loading 'src.datamodules.chexpert_datamodule.CheXpertDataModule':
ModuleNotFoundError("No module named 'albumentations'")
Are you sure that 'chexpert_datamodule' is importable from module 'src.datamodules'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 69, in train
    datamodule: LightningDataModule = hydra.utils.instantiate(cfg.datamodule)
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 222, in instantiate
    return instantiate_node(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 325, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.datamodules.chexpert_datamodule.CheXpertDataModule', see chained exception above.
full_key: datamodule
[2022-11-15 20:53:09,600][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 20:57:54,685][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 20:57:54,694][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 20:57:54,785][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 20:57:55,570][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 20:57:56,188][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 20:58:14,933][__main__][INFO] - Instantiating callbacks...
[2022-11-15 20:58:14,934][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 20:58:14,939][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 20:58:14,941][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 20:58:14,942][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 20:58:14,943][__main__][INFO] - Instantiating loggers...
[2022-11-15 20:58:14,943][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 20:58:15,429][__main__][INFO] - Starting training!
[2022-11-15 20:58:16,790][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3800, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Frontal/Lateral'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 98, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1107, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1449, in _call_setup_hook
    self._call_lightning_datamodule_hook("setup", stage=fn)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1571, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/datamodules/chexpert_datamodule.py", line 119, in setup
    self.data_test = chexpert.CheXpertDataset(self.hparams.data_dir, self.hparams.image_root_path, transforms=self.transforms_valid, mode='test')
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/datamodules/chexpert.py", line 41, in __init__
    self.df = self.df[self.df['Frontal/Lateral'] == 'Frontal']
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    raise KeyError(key) from err
KeyError: 'Frontal/Lateral'
[2022-11-15 20:58:16,796][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 21:04:42,763][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 21:04:42,771][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 21:04:42,860][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 21:04:43,627][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 21:04:44,242][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 21:04:44,385][__main__][INFO] - Instantiating callbacks...
[2022-11-15 21:04:44,385][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 21:04:44,390][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 21:04:44,392][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 21:04:44,393][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 21:04:44,394][__main__][INFO] - Instantiating loggers...
[2022-11-15 21:04:44,394][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 21:04:44,869][__main__][INFO] - Starting training!
[2022-11-15 21:04:46,473][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 98, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 127, in advance
    batch = next(data_fetcher)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 185, in __next__
    return self.fetching_function()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 264, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 278, in _fetch_next_batch
    batch = next(iterator)
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/datamodules/chexpert.py", line 171, in __getitem__
    image = self.transform(image=image)
AttributeError: 'CheXpertDataset' object has no attribute 'transform'
[2022-11-15 21:04:46,477][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 21:05:35,372][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 21:05:35,381][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 21:05:35,470][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 21:05:36,260][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 21:05:36,878][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 21:05:36,997][__main__][INFO] - Instantiating callbacks...
[2022-11-15 21:05:36,998][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 21:05:37,003][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 21:05:37,005][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 21:05:37,005][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 21:05:37,006][__main__][INFO] - Instantiating loggers...
[2022-11-15 21:05:37,007][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 21:05:37,485][__main__][INFO] - Starting training!
[2022-11-15 21:05:41,207][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 98, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 92, in validation_step
    loss, preds, targets = self.step(batch)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 69, in step
    loss = self.criterion(logits, y)
TypeError: 'DictConfig' object is not callable
[2022-11-15 21:05:41,210][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 21:06:26,495][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 21:06:26,504][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 21:06:26,594][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 21:06:27,381][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 21:06:27,997][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 21:06:28,109][__main__][INFO] - Instantiating callbacks...
[2022-11-15 21:06:28,110][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 21:06:28,115][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 21:06:28,117][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 21:06:28,117][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 21:06:28,118][__main__][INFO] - Instantiating loggers...
[2022-11-15 21:06:28,119][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 21:06:28,595][__main__][INFO] - Starting training!
[2022-11-15 21:06:32,422][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 98, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 92, in validation_step
    loss, preds, targets = self.step(batch)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 69, in step
    loss = self.criterion(logits, y)
TypeError: 'DictConfig' object is not callable
[2022-11-15 21:06:32,426][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 21:07:09,390][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 21:07:09,399][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 21:07:09,487][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 21:07:10,260][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 21:07:10,888][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 21:07:11,044][__main__][INFO] - Instantiating callbacks...
[2022-11-15 21:07:11,044][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 21:07:11,049][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 21:07:11,051][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 21:07:11,052][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 21:07:11,053][__main__][INFO] - Instantiating loggers...
[2022-11-15 21:07:11,053][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 21:07:11,531][__main__][INFO] - Starting training!
[2022-11-15 21:07:15,296][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 98, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 91, in validation_step
    loss, preds, targets = self.step(batch)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 68, in step
    loss = self.criterion(logits, y)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
[2022-11-15 21:07:15,300][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 21:11:41,508][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 21:11:41,518][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 21:11:41,607][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 21:11:42,362][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 21:11:42,977][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 21:11:43,092][__main__][INFO] - Instantiating callbacks...
[2022-11-15 21:11:43,093][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 21:11:43,098][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 21:11:43,100][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 21:11:43,101][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 21:11:43,101][__main__][INFO] - Instantiating loggers...
[2022-11-15 21:11:43,102][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 21:11:43,585][__main__][INFO] - Starting training!
[2022-11-15 21:11:46,803][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 98, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 91, in validation_step
    loss, preds, targets = self.step(batch)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 68, in step
    loss = self.criterion(logits, y)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1164, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/usr/local/lib/python3.8/site-packages/torch/nn/functional.py", line 3014, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: 0D or 1D target tensor expected, multi-target not supported
[2022-11-15 21:11:46,807][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 21:17:06,388][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 21:17:06,396][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 21:17:06,484][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 21:17:07,277][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 21:17:07,900][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 21:17:08,014][__main__][INFO] - Instantiating callbacks...
[2022-11-15 21:17:08,015][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 21:17:08,020][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 21:17:08,022][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 21:17:08,023][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 21:17:08,023][__main__][INFO] - Instantiating loggers...
[2022-11-15 21:17:08,024][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 21:17:08,508][__main__][INFO] - Starting training!
[2022-11-15 21:17:12,228][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 98, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 90, in validation_step
    loss, preds, targets = self.step(batch)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 67, in step
    loss = self.criterion(logits, y)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 841, in forward
    return F.multilabel_margin_loss(input, target, reduction=self.reduction)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/functional.py", line 3377, in multilabel_margin_loss
    return torch._C._nn.multilabel_margin_loss(input, target, reduction_enum)
RuntimeError: expected scalar type Long but found Float
[2022-11-15 21:17:12,233][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 21:19:13,862][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 21:19:13,871][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 21:19:13,959][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 21:19:14,744][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 21:19:15,360][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 21:19:15,503][__main__][INFO] - Instantiating callbacks...
[2022-11-15 21:19:15,503][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 21:19:15,508][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 21:19:15,510][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 21:19:15,511][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 21:19:15,512][__main__][INFO] - Instantiating loggers...
[2022-11-15 21:19:15,513][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 21:19:15,987][__main__][INFO] - Starting training!
[2022-11-15 21:19:19,633][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 98, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 90, in validation_step
    loss, preds, targets = self.step(batch)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 67, in step
    loss = self.criterion(logits, y)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 841, in forward
    return F.multilabel_margin_loss(input, target, reduction=self.reduction)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/functional.py", line 3377, in multilabel_margin_loss
    return torch._C._nn.multilabel_margin_loss(input, target, reduction_enum)
RuntimeError: expected scalar type Long but found Int
[2022-11-15 21:19:19,637][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 21:23:30,397][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 21:23:30,406][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 21:23:30,503][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 21:23:31,272][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 21:23:31,900][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 21:23:32,048][__main__][INFO] - Instantiating callbacks...
[2022-11-15 21:23:32,049][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 21:23:32,054][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 21:23:32,056][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 21:23:32,057][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 21:23:32,057][__main__][INFO] - Instantiating loggers...
[2022-11-15 21:23:32,058][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 21:23:32,533][__main__][INFO] - Starting training!
[2022-11-15 21:23:36,338][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 98, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 95, in validation_step
    self.val_acc(preds, targets)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/metric.py", line 245, in forward
    self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/metric.py", line 309, in _forward_reduce_state_update
    self.update(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/metric.py", line 395, in wrapped_func
    update(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/classification/accuracy.py", line 570, in update
    mode = _mode(preds, target, self.threshold, self.top_k, self.num_classes, self.multiclass, self.ignore_index)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/functional/classification/accuracy.py", line 423, in _mode
    mode = _check_classification_inputs(
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/utilities/checks.py", line 273, in _check_classification_inputs
    case, implied_classes = _check_shape_and_type_consistency(preds, target)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/utilities/checks.py", line 119, in _check_shape_and_type_consistency
    raise ValueError(
ValueError: Either `preds` and `target` both should have the (same) shape (N, ...), or `target` should be (N, ...) and `preds` should be (N, C, ...).
[2022-11-15 21:23:36,343][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 21:25:04,248][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 21:25:04,256][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 21:25:04,344][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 21:25:05,122][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 21:25:05,743][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 21:25:06,005][__main__][INFO] - Instantiating callbacks...
[2022-11-15 21:25:06,005][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 21:25:06,010][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 21:25:06,012][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 21:25:06,013][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 21:25:06,014][__main__][INFO] - Instantiating loggers...
[2022-11-15 21:25:06,014][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 21:25:06,505][__main__][INFO] - Starting training!
[2022-11-15 21:25:11,531][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 98, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 98, in validation_step
    self.val_acc(preds, targets)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/metric.py", line 245, in forward
    self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/metric.py", line 309, in _forward_reduce_state_update
    self.update(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/metric.py", line 395, in wrapped_func
    update(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/classification/accuracy.py", line 570, in update
    mode = _mode(preds, target, self.threshold, self.top_k, self.num_classes, self.multiclass, self.ignore_index)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/functional/classification/accuracy.py", line 423, in _mode
    mode = _check_classification_inputs(
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/utilities/checks.py", line 273, in _check_classification_inputs
    case, implied_classes = _check_shape_and_type_consistency(preds, target)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/utilities/checks.py", line 119, in _check_shape_and_type_consistency
    raise ValueError(
ValueError: Either `preds` and `target` both should have the (same) shape (N, ...), or `target` should be (N, ...) and `preds` should be (N, C, ...).
[2022-11-15 21:25:11,536][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 21:43:34,163][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 21:43:34,171][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 21:43:34,260][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 21:43:35,040][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 21:43:35,664][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 21:43:35,788][__main__][INFO] - Instantiating callbacks...
[2022-11-15 21:43:35,789][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 21:43:35,794][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 21:43:35,796][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 21:43:35,797][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 21:43:35,798][__main__][INFO] - Instantiating loggers...
[2022-11-15 21:43:35,798][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 21:43:36,292][__main__][INFO] - Starting training!
[2022-11-15 21:44:00,738][__main__][INFO] - Starting testing!
[2022-11-15 21:44:00,738][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2022-11-15 21:44:03,360][__main__][INFO] - Best ckpt path: None
[2022-11-15 21:44:03,363][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 21:44:03,364][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-15_21-43-34
[2022-11-15 21:44:03,364][src.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2022-11-15 21:44:31,502][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 21:44:31,511][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 21:44:31,602][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 21:44:32,368][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 21:44:32,988][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 21:44:33,103][__main__][INFO] - Instantiating callbacks...
[2022-11-15 21:44:33,104][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 21:44:33,109][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 21:44:33,111][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 21:44:33,111][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 21:44:33,112][__main__][INFO] - Instantiating loggers...
[2022-11-15 21:44:33,113][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 21:44:33,611][__main__][INFO] - Starting training!
[2022-11-15 21:45:03,644][__main__][INFO] - Starting testing!
[2022-11-15 21:45:03,644][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2022-11-15 21:45:03,821][__main__][INFO] - Best ckpt path: None
[2022-11-15 21:45:03,824][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 21:45:03,825][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-15_21-44-31
[2022-11-15 21:45:03,825][src.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2022-11-15 21:45:23,655][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 21:45:23,664][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 21:45:23,752][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 21:45:24,517][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 21:45:25,132][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 21:45:25,291][__main__][INFO] - Instantiating callbacks...
[2022-11-15 21:45:25,292][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 21:45:25,297][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 21:45:25,300][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 21:45:25,301][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 21:45:25,302][__main__][INFO] - Instantiating loggers...
[2022-11-15 21:45:25,303][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 21:45:25,801][__main__][INFO] - Starting training!
[2022-11-15 21:45:55,960][__main__][INFO] - Starting testing!
[2022-11-15 21:45:55,960][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2022-11-15 21:45:56,043][__main__][INFO] - Best ckpt path: None
[2022-11-15 21:45:56,046][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 21:45:56,047][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-15_21-45-23
[2022-11-15 21:45:56,048][src.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2022-11-15 21:46:45,788][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 21:46:45,796][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 21:46:45,884][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 21:46:46,652][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 21:46:47,265][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 21:46:47,378][__main__][INFO] - Instantiating callbacks...
[2022-11-15 21:46:47,379][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 21:46:47,384][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 21:46:47,386][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 21:46:47,387][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 21:46:47,388][__main__][INFO] - Instantiating loggers...
[2022-11-15 21:46:47,389][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 21:46:48,159][__main__][INFO] - Starting training!
[2022-11-15 21:47:33,986][__main__][INFO] - Starting testing!
[2022-11-15 21:47:33,986][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2022-11-15 21:47:34,306][__main__][INFO] - Best ckpt path: None
[2022-11-15 21:47:34,309][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 21:47:34,311][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-15_21-46-45
[2022-11-15 21:47:34,311][src.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2022-11-15 21:47:43,888][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 21:47:43,896][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 21:47:43,984][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 21:47:44,765][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 21:47:45,388][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 21:47:45,506][__main__][INFO] - Instantiating callbacks...
[2022-11-15 21:47:45,506][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 21:47:45,511][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 21:47:45,513][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 21:47:45,514][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 21:47:45,515][__main__][INFO] - Instantiating loggers...
[2022-11-15 21:47:45,515][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 21:47:46,314][__main__][INFO] - Starting training!
[2022-11-15 22:12:53,614][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 98, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1285, in _run_train
    self.fit_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 201, in run
    self.on_advance_end()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 298, in on_advance_end
    self.trainer._call_callback_hooks("on_train_epoch_end")
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1599, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 183, in on_train_epoch_end
    self._run_early_stopping_check(trainer)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 194, in _run_early_stopping_check
    if trainer.fast_dev_run or not self._validate_condition_metric(  # disable early_stopping with fast_dev_run
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 149, in _validate_condition_metric
    raise RuntimeError(error_msg)
RuntimeError: Early stopping conditioned on metric `val/acc` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: `val/loss`, `val/auc`, `val/auc_best`, `train/loss`, `train/auc`
[2022-11-15 22:12:53,618][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 22:15:31,688][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 22:15:31,697][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 22:15:31,786][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 22:15:32,561][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 22:15:33,188][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 22:15:33,301][__main__][INFO] - Instantiating callbacks...
[2022-11-15 22:15:33,302][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 22:15:33,307][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 22:15:33,309][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 22:15:33,310][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 22:15:33,310][__main__][INFO] - Instantiating loggers...
[2022-11-15 22:15:33,311][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 22:15:33,962][__main__][INFO] - Starting training!
[2022-11-15 22:35:55,213][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 22:35:55,222][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 22:35:55,316][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 22:35:55,320][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 639, in _locate
    obj = getattr(obj, part)
AttributeError: module 'src.datamodules' has no attribute 'chexpert_datamodule'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 645, in _locate
    obj = import_module(mod)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/datamodules/chexpert_datamodule.py", line 9, in <module>
    import albumentations as albu
ModuleNotFoundError: No module named 'albumentations'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 648, in _locate
    raise ImportError(
ImportError: Error loading 'src.datamodules.chexpert_datamodule.CheXpertDataModule':
ModuleNotFoundError("No module named 'albumentations'")
Are you sure that 'chexpert_datamodule' is importable from module 'src.datamodules'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 69, in train
    datamodule: LightningDataModule = hydra.utils.instantiate(cfg.datamodule)
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 222, in instantiate
    return instantiate_node(
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 325, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/usr/local/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.datamodules.chexpert_datamodule.CheXpertDataModule', see chained exception above.
full_key: datamodule
[2022-11-15 22:35:55,323][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 22:37:49,187][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 22:37:49,195][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 22:37:49,288][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 22:37:49,377][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 22:37:49,976][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 22:38:16,031][__main__][INFO] - Instantiating callbacks...
[2022-11-15 22:38:16,031][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 22:38:16,037][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 22:38:16,039][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 22:38:16,040][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 22:38:16,041][__main__][INFO] - Instantiating loggers...
[2022-11-15 22:38:16,041][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 22:38:16,197][__main__][INFO] - Starting training!
[2022-11-15 22:40:26,611][__main__][INFO] - Starting testing!
[2022-11-15 22:40:26,612][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2022-11-15 22:40:26,852][__main__][INFO] - Best ckpt path: None
[2022-11-15 22:40:26,856][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 22:40:26,857][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/multiruns/2022-11-15_22-37-47/0
[2022-11-15 22:41:43,297][__main__][INFO] - Starting testing!
[2022-11-15 22:41:43,519][__main__][INFO] - Best ckpt path: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-15_22-15-31/checkpoints/epoch_000.ckpt
[2022-11-15 22:41:43,522][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 22:41:43,523][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-15_22-15-31
[2022-11-15 22:41:43,524][src.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2022-11-15 22:41:49,455][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 22:41:49,464][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 22:41:49,554][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 22:41:50,333][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 22:41:50,952][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 22:41:51,068][__main__][INFO] - Instantiating callbacks...
[2022-11-15 22:41:51,069][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 22:41:51,074][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 22:41:51,076][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 22:41:51,076][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 22:41:51,077][__main__][INFO] - Instantiating loggers...
[2022-11-15 22:41:51,078][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 22:41:51,734][__main__][INFO] - Starting training!
[2022-11-15 22:42:10,573][__main__][INFO] - Starting testing!
[2022-11-15 22:42:10,574][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2022-11-15 22:42:12,825][__main__][INFO] - Best ckpt path: None
[2022-11-15 22:42:12,828][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 22:42:12,830][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-15_22-41-49
[2022-11-15 22:42:12,830][src.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2022-11-15 22:42:18,926][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 22:42:18,935][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 22:42:19,024][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 22:42:19,222][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 22:42:51,641][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 22:42:51,650][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 22:42:51,737][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 22:42:52,505][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 22:42:53,124][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 22:42:53,236][__main__][INFO] - Instantiating callbacks...
[2022-11-15 22:42:53,236][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 22:42:53,241][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 22:42:53,244][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 22:42:53,244][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 22:42:53,245][__main__][INFO] - Instantiating loggers...
[2022-11-15 22:42:53,246][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 22:42:53,899][__main__][INFO] - Starting training!
[2022-11-15 22:43:54,827][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 22:43:54,836][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 22:43:54,926][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 22:43:55,015][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 22:43:55,628][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 22:43:55,922][__main__][INFO] - Instantiating callbacks...
[2022-11-15 22:43:55,922][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 22:43:55,928][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 22:43:55,930][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 22:43:55,931][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 22:43:55,932][__main__][INFO] - Instantiating loggers...
[2022-11-15 22:43:55,932][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 22:43:56,149][__main__][INFO] - Starting training!
[2022-11-15 22:45:53,885][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 22:45:53,894][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 22:45:53,992][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 22:45:54,843][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 22:45:55,483][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 22:46:11,672][__main__][INFO] - Instantiating callbacks...
[2022-11-15 22:46:11,673][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 22:46:11,678][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 22:46:11,680][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 22:46:11,681][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 22:46:11,682][__main__][INFO] - Instantiating loggers...
[2022-11-15 22:46:11,682][src.utils.utils][INFO] - Instantiating logger <pytorch_lightning.loggers.wandb.WandbLogger>
[2022-11-15 22:47:34,197][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 22:47:34,628][__main__][INFO] - Logging hyperparameters!
[2022-11-15 22:47:34,645][__main__][INFO] - Starting training!
[2022-11-15 23:10:28,040][__main__][INFO] - Starting testing!
[2022-11-15 23:10:28,284][__main__][INFO] - Best ckpt path: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-15_22-45-53/checkpoints/epoch_001.ckpt
[2022-11-15 23:10:28,289][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 23:10:28,290][src.utils.utils][INFO] - Closing wandb!
[2022-11-15 23:10:32,340][__main__][INFO] - Starting testing!
[2022-11-15 23:10:32,543][__main__][INFO] - Best ckpt path: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/multiruns/2022-11-15_22-43-53/0/checkpoints/epoch_000.ckpt
[2022-11-15 23:10:32,548][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 23:10:32,549][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/multiruns/2022-11-15_22-43-53/0
[2022-11-15 23:10:32,550][src.utils.utils][INFO] - Retrieved metric value! <val/auc_best=0.49828988313674927>
[2022-11-15 23:10:35,795][__main__][INFO] - Starting testing!
[2022-11-15 23:10:36,037][__main__][INFO] - Best ckpt path: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-15_22-42-51/checkpoints/epoch_001.ckpt
[2022-11-15 23:10:36,042][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 23:10:36,043][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-15_22-42-51
[2022-11-15 23:10:36,044][src.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2022-11-15 23:11:23,139][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 23:11:23,148][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 23:11:23,237][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 23:11:24,025][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 23:11:24,657][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 23:11:24,796][__main__][INFO] - Instantiating callbacks...
[2022-11-15 23:11:24,797][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 23:11:24,802][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 23:11:24,804][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 23:11:24,804][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 23:11:24,805][__main__][INFO] - Instantiating loggers...
[2022-11-15 23:11:24,806][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 23:11:25,603][__main__][INFO] - Starting training!
[2022-11-15 23:11:49,293][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 23:11:49,302][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 23:11:49,397][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 23:11:50,182][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 23:11:50,802][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 23:11:51,071][__main__][INFO] - Instantiating callbacks...
[2022-11-15 23:11:51,071][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 23:11:51,077][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 23:11:51,079][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 23:11:51,080][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 23:11:51,080][__main__][INFO] - Instantiating loggers...
[2022-11-15 23:11:51,081][src.utils.utils][INFO] - Instantiating logger <pytorch_lightning.loggers.wandb.WandbLogger>
[2022-11-15 23:11:53,849][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 23:11:54,265][__main__][INFO] - Logging hyperparameters!
[2022-11-15 23:11:54,282][__main__][INFO] - Starting training!
[2022-11-15 23:12:13,076][__main__][INFO] - Starting testing!
[2022-11-15 23:12:13,102][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2022-11-15 23:12:13,495][__main__][INFO] - Best ckpt path: None
[2022-11-15 23:12:13,499][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 23:12:13,500][src.utils.utils][INFO] - Closing wandb!
[2022-11-15 23:12:15,548][__main__][INFO] - Starting testing!
[2022-11-15 23:12:15,549][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2022-11-15 23:12:18,347][__main__][INFO] - Best ckpt path: None
[2022-11-15 23:12:18,352][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 23:12:18,354][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-15_23-11-22
[2022-11-15 23:12:18,368][src.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2022-11-15 23:13:03,043][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 23:13:03,052][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 23:13:03,141][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 23:13:03,924][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 23:13:04,543][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 23:13:04,670][__main__][INFO] - Instantiating callbacks...
[2022-11-15 23:13:04,671][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 23:13:04,676][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 23:13:04,678][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 23:13:04,679][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 23:13:04,679][__main__][INFO] - Instantiating loggers...
[2022-11-15 23:13:04,680][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 23:13:05,505][__main__][INFO] - Starting training!
[2022-11-15 23:13:11,024][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 23:13:11,035][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 23:13:11,135][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 23:13:11,946][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 23:13:12,584][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 23:13:12,866][__main__][INFO] - Instantiating callbacks...
[2022-11-15 23:13:12,867][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 23:13:12,872][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 23:13:12,874][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 23:13:12,875][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 23:13:12,876][__main__][INFO] - Instantiating loggers...
[2022-11-15 23:13:12,876][src.utils.utils][INFO] - Instantiating logger <pytorch_lightning.loggers.wandb.WandbLogger>
[2022-11-15 23:13:15,899][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 23:13:16,612][__main__][INFO] - Logging hyperparameters!
[2022-11-15 23:13:16,628][__main__][INFO] - Starting training!
[2022-11-15 23:13:17,429][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 23:13:17,438][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 23:13:17,532][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 23:13:17,622][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 23:13:18,228][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
[2022-11-15 23:13:18,496][__main__][INFO] - Instantiating callbacks...
[2022-11-15 23:13:18,497][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 23:13:18,502][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 23:13:18,504][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 23:13:18,505][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 23:13:18,505][__main__][INFO] - Instantiating loggers...
[2022-11-15 23:13:18,506][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 23:13:18,754][__main__][INFO] - Starting training!
[2022-11-15 23:14:20,387][__main__][INFO] - Starting testing!
[2022-11-15 23:14:20,399][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2022-11-15 23:14:21,028][__main__][INFO] - Best ckpt path: None
[2022-11-15 23:14:21,033][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 23:14:21,035][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-15_23-13-02
[2022-11-15 23:14:21,035][src.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2022-11-15 23:14:25,265][__main__][INFO] - Starting testing!
[2022-11-15 23:14:25,266][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2022-11-15 23:14:25,573][__main__][INFO] - Best ckpt path: None
[2022-11-15 23:14:25,579][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 23:14:25,580][src.utils.utils][INFO] - Closing wandb!
[2022-11-15 23:14:27,161][__main__][INFO] - Starting testing!
[2022-11-15 23:14:27,162][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2022-11-15 23:14:34,858][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1163, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 108, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 108, in train
    trainer.test(model=model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 911, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1251, in _run_stage
    return self._run_evaluate()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1297, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 127, in advance
    batch = next(data_fetcher)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 185, in __next__
    return self.fetching_function()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 264, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 278, in _fetch_next_batch
    batch = next(iterator)
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _next_data
    idx, data = self._get_data()
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1325, in _get_data
    success, data = self._try_get_data()
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1176, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 58954) exited unexpectedly
[2022-11-15 23:14:34,866][src.utils.utils][INFO] - Closing loggers...
[2022-11-15 23:14:48,374][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 23:14:48,383][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 23:14:48,469][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 23:14:49,237][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 23:14:49,593][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/densenet121_ra-50efcf5c.pth)
[2022-11-15 23:14:53,815][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 23:14:53,823][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 23:14:53,918][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 23:14:54,704][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 23:14:55,065][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/densenet121_ra-50efcf5c.pth)
[2022-11-15 23:14:56,646][__main__][INFO] - Instantiating callbacks...
[2022-11-15 23:14:56,647][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 23:14:56,652][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 23:14:56,654][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 23:14:56,655][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 23:14:56,655][__main__][INFO] - Instantiating loggers...
[2022-11-15 23:14:56,656][src.utils.utils][INFO] - Instantiating logger <pytorch_lightning.loggers.wandb.WandbLogger>
[2022-11-15 23:14:56,689][__main__][INFO] - Instantiating callbacks...
[2022-11-15 23:14:56,689][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 23:14:56,694][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 23:14:56,696][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 23:14:56,697][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 23:14:56,698][__main__][INFO] - Instantiating loggers...
[2022-11-15 23:14:56,698][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 23:14:57,722][__main__][INFO] - Starting training!
[2022-11-15 23:14:59,081][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-15 23:14:59,090][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-15 23:14:59,178][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-15 23:14:59,264][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-15 23:14:59,607][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/densenet121_ra-50efcf5c.pth)
[2022-11-15 23:14:59,609][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 23:14:59,864][__main__][INFO] - Logging hyperparameters!
[2022-11-15 23:14:59,884][__main__][INFO] - Starting training!
[2022-11-15 23:15:00,546][__main__][INFO] - Instantiating callbacks...
[2022-11-15 23:15:00,546][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-15 23:15:00,552][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-15 23:15:00,553][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-15 23:15:00,554][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-15 23:15:00,555][__main__][INFO] - Instantiating loggers...
[2022-11-15 23:15:00,556][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-15 23:15:00,788][__main__][INFO] - Starting training!
[2022-11-16 00:07:31,586][__main__][INFO] - Starting testing!
[2022-11-16 00:07:31,983][__main__][INFO] - Best ckpt path: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-15_23-14-48/checkpoints/epoch_002.ckpt
[2022-11-16 00:07:31,986][src.utils.utils][INFO] - Closing loggers...
[2022-11-16 00:07:31,989][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-15_23-14-48
[2022-11-16 00:07:31,989][src.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2022-11-16 00:07:33,563][__main__][INFO] - Starting testing!
[2022-11-16 00:07:33,859][__main__][INFO] - Best ckpt path: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-15_23-14-53/checkpoints/epoch_000.ckpt
[2022-11-16 00:07:33,864][src.utils.utils][INFO] - Closing loggers...
[2022-11-16 00:07:33,865][src.utils.utils][INFO] - Closing wandb!
[2022-11-16 00:07:35,913][__main__][INFO] - Starting testing!
[2022-11-16 00:07:36,143][__main__][INFO] - Best ckpt path: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/multiruns/2022-11-15_23-14-57/0/checkpoints/epoch_000.ckpt
[2022-11-16 00:07:36,147][src.utils.utils][INFO] - Closing loggers...
[2022-11-16 00:07:36,149][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/multiruns/2022-11-15_23-14-57/0
[2022-11-16 00:07:36,149][src.utils.utils][INFO] - Retrieved metric value! <val/auc_best=0.5089020729064941>
[2022-11-16 00:08:59,846][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-16 00:08:59,855][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-16 00:08:59,943][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-16 00:09:00,735][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-16 00:09:01,099][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/densenet121_ra-50efcf5c.pth)
[2022-11-16 00:09:01,260][__main__][INFO] - Instantiating callbacks...
[2022-11-16 00:09:01,260][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-16 00:09:01,265][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-16 00:09:01,267][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-16 00:09:01,268][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-16 00:09:01,269][__main__][INFO] - Instantiating loggers...
[2022-11-16 00:09:01,269][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-16 00:09:02,256][__main__][INFO] - Starting training!
[2022-11-16 00:09:10,684][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 98, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 95, in validation_step
    loss, preds, targets = self.step(batch)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 70, in step
    loss = self.criterion(logits, y)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 714, in forward
    return F.binary_cross_entropy_with_logits(input, target,
  File "/usr/local/lib/python3.8/site-packages/torch/nn/functional.py", line 3150, in binary_cross_entropy_with_logits
    return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
RuntimeError: result type Float can't be cast to the desired output type Long
[2022-11-16 00:09:10,691][src.utils.utils][INFO] - Closing loggers...
[2022-11-16 00:11:24,549][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-16 00:11:24,559][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-16 00:11:24,659][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-16 00:11:25,488][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-16 00:11:25,845][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/densenet121_ra-50efcf5c.pth)
[2022-11-16 00:11:26,004][__main__][INFO] - Instantiating callbacks...
[2022-11-16 00:11:26,005][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-16 00:11:26,010][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-16 00:11:26,012][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-16 00:11:26,013][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-16 00:11:26,014][__main__][INFO] - Instantiating loggers...
[2022-11-16 00:11:26,014][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-16 00:11:26,990][__main__][INFO] - Starting training!
[2022-11-16 00:11:35,455][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 98, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 96, in validation_step
    loss, preds, targets = self.step(batch)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 71, in step
    loss = self.criterion(logits, y)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 714, in forward
    return F.binary_cross_entropy_with_logits(input, target,
  File "/usr/local/lib/python3.8/site-packages/torch/nn/functional.py", line 3150, in binary_cross_entropy_with_logits
    return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
RuntimeError: result type Float can't be cast to the desired output type Long
[2022-11-16 00:11:35,464][src.utils.utils][INFO] - Closing loggers...
[2022-11-16 00:13:16,066][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-16 00:13:16,074][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-16 00:13:16,163][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-16 00:13:16,962][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-16 00:13:17,318][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/densenet121_ra-50efcf5c.pth)
[2022-11-16 00:13:17,456][__main__][INFO] - Instantiating callbacks...
[2022-11-16 00:13:17,457][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-16 00:13:17,461][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-16 00:13:17,463][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-16 00:13:17,464][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-16 00:13:17,465][__main__][INFO] - Instantiating loggers...
[2022-11-16 00:13:17,465][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-16 00:13:18,442][__main__][INFO] - Starting training!
[2022-11-16 00:13:26,778][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 98, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 100, in validation_step
    self.val_auc(preds, targets)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/metric.py", line 245, in forward
    self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/metric.py", line 309, in _forward_reduce_state_update
    self.update(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/metric.py", line 405, in wrapped_func
    raise err
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/metric.py", line 395, in wrapped_func
    update(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/classification/precision_recall_curve.py", line 409, in update
    state = _multilabel_precision_recall_curve_update(preds, target, self.num_labels, self.thresholds)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/functional/classification/precision_recall_curve.py", line 631, in _multilabel_precision_recall_curve_update
    bins = _bincount(unique_mapping, minlength=4 * num_labels * len_t)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/utilities/data.py", line 246, in _bincount
    return z.index_add_(0, x, torch.ones_like(x))
RuntimeError: index_add_(): Expected dtype int32/int64 for index but got: Float
[2022-11-16 00:13:26,789][src.utils.utils][INFO] - Closing loggers...
[2022-11-16 00:14:26,153][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-16 00:14:26,161][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-16 00:14:26,248][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-16 00:14:27,054][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-16 00:14:27,409][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/densenet121_ra-50efcf5c.pth)
[2022-11-16 00:14:27,590][__main__][INFO] - Instantiating callbacks...
[2022-11-16 00:14:27,591][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-16 00:14:27,596][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-16 00:14:27,598][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-16 00:14:27,599][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-16 00:14:27,599][__main__][INFO] - Instantiating loggers...
[2022-11-16 00:14:27,600][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-16 00:14:28,576][__main__][INFO] - Starting training!
[2022-11-16 00:14:37,198][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 98, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 96, in validation_step
    loss, preds, targets = self.step(batch)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 71, in step
    loss = self.criterion(logits, y)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 714, in forward
    return F.binary_cross_entropy_with_logits(input, target,
  File "/usr/local/lib/python3.8/site-packages/torch/nn/functional.py", line 3150, in binary_cross_entropy_with_logits
    return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
RuntimeError: result type Float can't be cast to the desired output type Int
[2022-11-16 00:14:37,205][src.utils.utils][INFO] - Closing loggers...
[2022-11-16 00:18:19,867][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-16 00:18:19,876][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-16 00:18:19,963][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-16 00:18:20,767][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-16 00:18:21,125][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/densenet121_ra-50efcf5c.pth)
[2022-11-16 00:18:21,300][__main__][INFO] - Instantiating callbacks...
[2022-11-16 00:18:21,300][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-16 00:18:21,305][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-16 00:18:21,307][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-16 00:18:21,308][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-16 00:18:21,309][__main__][INFO] - Instantiating loggers...
[2022-11-16 00:18:21,310][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-16 00:18:22,268][__main__][INFO] - Starting training!
[2022-11-16 00:18:30,640][src.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "src/train.py", line 98, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1254, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1706, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 370, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/ubuntu/yisakk/Template/template_pl-hydra/src/models/timm_module.py", line 101, in validation_step
    self.val_auc(preds, targets)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/metric.py", line 245, in forward
    self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/metric.py", line 309, in _forward_reduce_state_update
    self.update(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/metric.py", line 405, in wrapped_func
    raise err
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/metric.py", line 395, in wrapped_func
    update(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/classification/precision_recall_curve.py", line 409, in update
    state = _multilabel_precision_recall_curve_update(preds, target, self.num_labels, self.thresholds)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/functional/classification/precision_recall_curve.py", line 631, in _multilabel_precision_recall_curve_update
    bins = _bincount(unique_mapping, minlength=4 * num_labels * len_t)
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/utilities/data.py", line 246, in _bincount
    return z.index_add_(0, x, torch.ones_like(x))
RuntimeError: index_add_(): Expected dtype int32/int64 for index but got: Float
[2022-11-16 00:18:30,647][src.utils.utils][INFO] - Closing loggers...
[2022-11-16 00:18:52,588][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-16 00:18:52,597][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-16 00:18:52,690][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-16 00:18:53,502][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-16 00:18:53,862][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/densenet121_ra-50efcf5c.pth)
[2022-11-16 00:18:54,061][__main__][INFO] - Instantiating callbacks...
[2022-11-16 00:18:54,062][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-16 00:18:54,067][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-16 00:18:54,069][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-16 00:18:54,070][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-16 00:18:54,070][__main__][INFO] - Instantiating loggers...
[2022-11-16 00:18:54,071][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-16 00:18:55,054][__main__][INFO] - Starting training!
[2022-11-16 00:19:26,403][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-16 00:19:26,412][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-16 00:19:26,506][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-16 00:19:27,339][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-16 00:19:27,698][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/densenet121_ra-50efcf5c.pth)
[2022-11-16 00:19:28,193][__main__][INFO] - Instantiating callbacks...
[2022-11-16 00:19:28,194][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-16 00:19:28,199][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-16 00:19:28,201][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-16 00:19:28,202][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-16 00:19:28,203][__main__][INFO] - Instantiating loggers...
[2022-11-16 00:19:28,203][src.utils.utils][INFO] - Instantiating logger <pytorch_lightning.loggers.wandb.WandbLogger>
[2022-11-16 00:19:31,164][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-16 00:19:31,407][__main__][INFO] - Logging hyperparameters!
[2022-11-16 00:19:31,428][__main__][INFO] - Starting training!
[2022-11-16 00:19:31,575][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-16 00:19:31,584][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-16 00:19:31,673][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-16 00:19:31,764][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-16 00:19:32,110][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/densenet121_ra-50efcf5c.pth)
[2022-11-16 00:19:32,589][__main__][INFO] - Instantiating callbacks...
[2022-11-16 00:19:32,590][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-16 00:19:32,595][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-16 00:19:32,597][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-16 00:19:32,598][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-16 00:19:32,598][__main__][INFO] - Instantiating loggers...
[2022-11-16 00:19:32,599][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-16 00:19:32,852][__main__][INFO] - Starting training!
[2022-11-16 02:35:47,088][__main__][INFO] - Starting testing!
[2022-11-16 02:35:52,105][__main__][INFO] - Best ckpt path: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-16_00-18-52/checkpoints/epoch_002.ckpt
[2022-11-16 02:35:52,108][src.utils.utils][INFO] - Closing loggers...
[2022-11-16 02:35:52,110][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-16_00-18-52
[2022-11-16 02:35:52,110][src.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2022-11-16 02:36:23,555][__main__][INFO] - Starting testing!
[2022-11-16 02:36:27,672][__main__][INFO] - Best ckpt path: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/multiruns/2022-11-16_00-19-29/0/checkpoints/epoch_009.ckpt
[2022-11-16 02:36:27,675][src.utils.utils][INFO] - Closing loggers...
[2022-11-16 02:36:27,677][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/multiruns/2022-11-16_00-19-29/0
[2022-11-16 02:36:27,677][src.utils.utils][INFO] - Retrieved metric value! <val/auc_best=0.7667760252952576>
[2022-11-16 02:36:28,057][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-16 02:36:28,061][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-16 02:36:28,151][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-16 02:36:28,157][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-16 02:36:28,356][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/densenet121_ra-50efcf5c.pth)
[2022-11-16 02:36:28,848][__main__][INFO] - Instantiating callbacks...
[2022-11-16 02:36:28,848][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-16 02:36:28,853][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-16 02:36:28,855][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-16 02:36:28,856][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-16 02:36:28,856][__main__][INFO] - Instantiating loggers...
[2022-11-16 02:36:28,857][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-16 02:36:29,847][__main__][INFO] - Starting training!
[2022-11-16 02:36:55,833][__main__][INFO] - Starting testing!
[2022-11-16 02:37:00,385][__main__][INFO] - Best ckpt path: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-16_00-19-26/checkpoints/epoch_002.ckpt
[2022-11-16 02:37:00,388][src.utils.utils][INFO] - Closing loggers...
[2022-11-16 02:37:00,389][src.utils.utils][INFO] - Closing wandb!
[2022-11-16 02:37:07,275][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/runs/2022-11-16_00-19-26
[2022-11-16 02:37:07,276][src.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2022-11-16 04:52:17,780][__main__][INFO] - Starting testing!
[2022-11-16 04:52:21,542][__main__][INFO] - Best ckpt path: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/multiruns/2022-11-16_00-19-29/1/checkpoints/epoch_006.ckpt
[2022-11-16 04:52:21,550][src.utils.utils][INFO] - Closing loggers...
[2022-11-16 04:52:21,552][src.utils.utils][INFO] - Output dir: /home/ubuntu/yisakk/Template/template_pl-hydra/logs/train/multiruns/2022-11-16_00-19-29/1
[2022-11-16 04:52:21,552][src.utils.utils][INFO] - Retrieved metric value! <val/auc_best=0.7535185813903809>
[2022-11-16 04:52:21,928][src.utils.utils][INFO] - Enforcing tags! <cfg.extras.enforce_tags=True>
[2022-11-16 04:52:21,931][src.utils.utils][INFO] - Printing config tree with Rich! <cfg.extras.print_config=True>
[2022-11-16 04:52:22,011][__main__][INFO] - Instantiating datamodule <src.datamodules.chexpert_datamodule.CheXpertDataModule>
[2022-11-16 04:52:22,016][__main__][INFO] - Instantiating model <src.models.timm_module.TimmLitModule>
[2022-11-16 04:52:22,561][timm.models.helpers][INFO] - Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/densenet121_ra-50efcf5c.pth)
[2022-11-16 04:52:22,804][__main__][INFO] - Instantiating callbacks...
[2022-11-16 04:52:22,805][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
[2022-11-16 04:52:22,810][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>
[2022-11-16 04:52:22,812][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>
[2022-11-16 04:52:22,813][src.utils.utils][INFO] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>
[2022-11-16 04:52:22,814][__main__][INFO] - Instantiating loggers...
[2022-11-16 04:52:22,814][__main__][INFO] - Instantiating trainer <pytorch_lightning.Trainer>
[2022-11-16 04:52:23,843][__main__][INFO] - Starting training!
